package rpgame;

public class CombatPrototypeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CombatPrototypeGUI.class.getName());


    Enemy e = new Enemy(1);
    PlayerClass p = new Mage();
    
    Combat combat = new Combat(p,e);
    
    int turnCount = 1;
    
    public CombatPrototypeGUI() {
        initComponents();
        
        abilitySelectionPanel.setVisible(false); 
        combatTracker();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enemyHealthLabel = new javax.swing.JLabel();
        enemyAttackPowerLabel = new javax.swing.JLabel();
        enemyManaLabel = new javax.swing.JLabel();
        enemyAbilityPowerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        playerAttackPowerLabel = new javax.swing.JLabel();
        playerHealthLabel = new javax.swing.JLabel();
        playerManaLabel = new javax.swing.JLabel();
        playerAbilityPowerLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        turnLabel = new javax.swing.JLabel();
        attackButton = new javax.swing.JButton();
        abilityButton = new javax.swing.JButton();
        defenceButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        abilitySelectionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        useAbility1 = new javax.swing.JButton();
        useAbility2 = new javax.swing.JButton();
        useAbility3 = new javax.swing.JButton();
        useAbility4 = new javax.swing.JButton();
        useAbility5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Enemy");

        enemyHealthLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enemyHealthLabel.setText("Health");

        enemyAttackPowerLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enemyAttackPowerLabel.setText("AttackPower");

        enemyManaLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enemyManaLabel.setText("Mana");

        enemyAbilityPowerLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enemyAbilityPowerLabel.setText("AbilityPower");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(enemyHealthLabel)
                    .addComponent(enemyAttackPowerLabel)
                    .addComponent(enemyManaLabel)
                    .addComponent(enemyAbilityPowerLabel))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(enemyHealthLabel)
                .addGap(29, 29, 29)
                .addComponent(enemyAttackPowerLabel)
                .addGap(29, 29, 29)
                .addComponent(enemyManaLabel)
                .addGap(29, 29, 29)
                .addComponent(enemyAbilityPowerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("You");

        playerAttackPowerLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        playerAttackPowerLabel.setText("AttackPower");

        playerHealthLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        playerHealthLabel.setText("Health");

        playerManaLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        playerManaLabel.setText("Mana");

        playerAbilityPowerLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        playerAbilityPowerLabel.setText("AbilityPower");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(playerHealthLabel)
                        .addComponent(playerAttackPowerLabel)
                        .addComponent(playerManaLabel)
                        .addComponent(playerAbilityPowerLabel))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(playerHealthLabel)
                .addGap(29, 29, 29)
                .addComponent(playerAttackPowerLabel)
                .addGap(29, 29, 29)
                .addComponent(playerManaLabel)
                .addGap(29, 29, 29)
                .addComponent(playerAbilityPowerLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        turnLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        turnLabel.setText("Turn");

        attackButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        attackButton.setText("Attack");
        attackButton.addActionListener(this::attackButtonActionPerformed);

        abilityButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        abilityButton.setText("Ability");
        abilityButton.addActionListener(this::abilityButtonActionPerformed);

        defenceButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        defenceButton.setText("Defence");
        defenceButton.addActionListener(this::defenceButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(attackButton)
                        .addComponent(abilityButton)
                        .addComponent(defenceButton))
                    .addComponent(turnLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defenceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setText("Log");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel3.setText("PLAYER used ...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(135, 135, 135))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setText("Player Abilities");

        useAbility1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        useAbility1.setText("Ability1");
        useAbility1.addActionListener(this::useAbility1ActionPerformed);

        useAbility2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        useAbility2.setText("Ability2");
        useAbility2.addActionListener(this::useAbility2ActionPerformed);

        useAbility3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        useAbility3.setText("Ability3");
        useAbility3.addActionListener(this::useAbility3ActionPerformed);

        useAbility4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        useAbility4.setText("Ability4");
        useAbility4.addActionListener(this::useAbility4ActionPerformed);

        useAbility5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        useAbility5.setText("Ability5");
        useAbility5.setToolTipText("");
        useAbility5.addActionListener(this::useAbility5ActionPerformed);

        javax.swing.GroupLayout abilitySelectionPanelLayout = new javax.swing.GroupLayout(abilitySelectionPanel);
        abilitySelectionPanel.setLayout(abilitySelectionPanelLayout);
        abilitySelectionPanelLayout.setHorizontalGroup(
            abilitySelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySelectionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(abilitySelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(abilitySelectionPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(abilitySelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useAbility1)
                            .addComponent(useAbility2)
                            .addComponent(useAbility3)
                            .addComponent(useAbility4)
                            .addComponent(useAbility5))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        abilitySelectionPanelLayout.setVerticalGroup(
            abilitySelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySelectionPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useAbility1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useAbility2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useAbility3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useAbility4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useAbility5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abilitySelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(abilitySelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abilityButtonActionPerformed

        playerButtons(abilityButton.getText());
    }//GEN-LAST:event_abilityButtonActionPerformed

    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed
        
        playerButtons(attackButton.getText());
    }//GEN-LAST:event_attackButtonActionPerformed

    private void defenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenceButtonActionPerformed

        playerButtons(defenceButton.getText());
    }//GEN-LAST:event_defenceButtonActionPerformed

    private void useAbility1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAbility1ActionPerformed
        
        playerButtons(useAbility1.getText());
    }//GEN-LAST:event_useAbility1ActionPerformed

    private void useAbility2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAbility2ActionPerformed
        
        playerButtons(useAbility2.getText());
    }//GEN-LAST:event_useAbility2ActionPerformed

    private void useAbility3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAbility3ActionPerformed
        
        playerButtons(useAbility3.getText());
    }//GEN-LAST:event_useAbility3ActionPerformed

    private void useAbility4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAbility4ActionPerformed
        
        playerButtons(useAbility4.getText());
    }//GEN-LAST:event_useAbility4ActionPerformed

    private void useAbility5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAbility5ActionPerformed
        
        playerButtons(useAbility5.getText());
    }//GEN-LAST:event_useAbility5ActionPerformed

    
    public void playerButtons(String buttonName){
        
        boolean isNextTurn = true;
        boolean abilitySelection = false;
        
        if (abilityButton.getText() == buttonName){
        
            isNextTurn = false;
            abilitySelection = true;
        }
        if (attackButton.getText() == buttonName){
            p.attack(e);
        }
        if(defenceButton.getText() == buttonName){
            
            
        }
        
        
        if(useAbility1.getText() == buttonName){
            
            p.useAbility(p.getAbility(0),e);
        }
        
        if(useAbility2.getText() == buttonName){
            p.useAbility(p.getAbility(1),e);
        }
        
        if(useAbility3.getText() == buttonName){
            p.useAbility(p.getAbility(2),e);
        }
        
        if(useAbility4.getText() == buttonName){
            p.useAbility(p.getAbility(3),e);
        }
        
        if(useAbility5.getText() == buttonName){
            p.useAbility(p.getAbility(4),e);
        }
    
        
        if(isNextTurn){
            combat.nextTurn();
        }
        
        if(abilitySelection){
            abilitySelectionPanel.setVisible(true);
        } else {
            abilitySelectionPanel.setVisible(false);
        }
    
        combatTracker();
    }
    
    
    
    public void updateLabels(){
        
        
        useAbility1.setText(p.getAbility(0).name);
        useAbility2.setText(p.getAbility(1).name);
        useAbility3.setText(p.getAbility(2).name);
        useAbility4.setText(p.getAbility(3).name);
        useAbility5.setText(p.getAbility(4).name);
        
        enemyAbilityPowerLabel.setText("AbilityPower: " + e.abilityPower);
        enemyAttackPowerLabel.setText("AttackPower: " + e.attackPower);
        enemyHealthLabel.setText("Health: " + e.HP + " / " + e.maxHP);
        enemyManaLabel.setText("Mana: " + e.mana);
        
        
        playerAbilityPowerLabel.setText("AbilityPower: " + p.abilityPower);
        playerAttackPowerLabel.setText("AttackPower: " + p.attackPower);
        playerHealthLabel.setText("Health: " + p.HP + " / " + p.maxHP);
        playerManaLabel.setText("Mana: " + p.mana);
        
        
        jLabel3.setText("TurnCount: " + turnCount);
        turnLabel.setText("Turn:" + combat.getTurn());

    }
    
    
    public void combatTracker(){
    
        updateLabels();        

        //while(p.HP > 0 && e.HP > 0){
        EntityType turn = combat.getTurn();
            
            
            if(EntityType.Player == turn){
                abilityButton.setEnabled(true);
                attackButton.setEnabled(true);
                defenceButton.setEnabled(true);
            } else {
                
                abilityButton.setEnabled(false);
                attackButton.setEnabled(false);
                defenceButton.setEnabled(false);
                
                
                e.checkStatus();
                e.turn(p); 
                e.statusFix();
                
                combat.nextTurn();
                
                combatTracker();
            }

            turnCount++;
        
    }
    
    
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(() -> new CombatPrototypeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abilityButton;
    private javax.swing.JPanel abilitySelectionPanel;
    private javax.swing.JButton attackButton;
    private javax.swing.JButton defenceButton;
    private javax.swing.JLabel enemyAbilityPowerLabel;
    private javax.swing.JLabel enemyAttackPowerLabel;
    private javax.swing.JLabel enemyHealthLabel;
    private javax.swing.JLabel enemyManaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel playerAbilityPowerLabel;
    private javax.swing.JLabel playerAttackPowerLabel;
    private javax.swing.JLabel playerHealthLabel;
    private javax.swing.JLabel playerManaLabel;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JButton useAbility1;
    private javax.swing.JButton useAbility2;
    private javax.swing.JButton useAbility3;
    private javax.swing.JButton useAbility4;
    private javax.swing.JButton useAbility5;
    // End of variables declaration//GEN-END:variables
}
